admin_user:
  username: harshith@yopmail.com	
  password: Qwinix123

common_user:
  username : john13@yopmail.com 
  password : Qwinix123

invalid_user:
  username : hychandrashekarr@qwinixtech.com
  password : Qwinix1233


